#include <avr/io.h>

#include <stdint.h>

#include "buzzer.h"

// Values used to write to the TCA0.SINGLE.PERBUF register.
#define TONE1_PER 354
#define TONE2_PER 297
#define TONE3_PER 472
#define TONE4_PER 177

/** EX: 12.3

TASK: Implement the functions below to turn the buzzer ON and OFF.

The "buzzer_on" function should take a single argument, "tone", which
ranges from 0 to 3 (or 1 to 4, whichever is more convenient), and sets
the frequency of the waveform output generated by TCA0 correspondingly.

Ensure that the above macros reflect the four frequencies required.
*/

void buzzer_on(const uint8_t tone)
{
    static const uint16_t periods[4] = {TONE1_PER, TONE2_PER, TONE3_PER, TONE4_PER};

    /** CODE: Write your code for Ex 12.3 within this function. */

    // Check if the tone value is valid
    if (tone > 3) return;

    // Set the period for TCA0
    TCA0.SINGLE.PER = periods[tone];

    // Set duty cycle to 50%. 
    TCA0.SINGLE.CMP0 = periods[tone] / 2;

}

void buzzer_off(void)
{
    /** CODE: Write your code for Ex 12.3 within this function. */
    
    // To make the buzzer silent, set the duty cycle to 0.
    TCA0.SINGLE.CMP0 = 0;

}
